// Generated by CoffeeScript 1.3.3
(function() {
  var Grid, Square;

  document.write("classes.js loaded");

  Square = (function() {

    Square.Colors = {
      Red: 1,
      Green: 2,
      Blue: 3
    };

    function Square(color, width, height) {
      this.color = color;
      this.width = width;
      this.height = height;
    }

    return Square;

  })();

  Grid = (function() {
    var squares;

    squares = [gwidth][gheight];

    function Grid(gwidth, gheight, swidth, sheight) {
      var i, j, _i, _j;
      this.gwidth = gwidth;
      this.gheight = gheight;
      for (i = _i = 1; 1 <= width ? _i <= width : _i >= width; i = 1 <= width ? ++_i : --_i) {
        for (j = _j = 1; 1 <= height ? _j <= height : _j >= height; j = 1 <= height ? ++_j : --_j) {
          square[i][j] = new Square;
          square[i][j].color = Square.Colors[Math.floor(Math.random() * 3) + 1];
          square[i][j].width = swidth;
          square[i][j].height = sheight;
        }
      }
    }

    return Grid;

  })();

}).call(this);
