// Generated by CoffeeScript 1.3.3
(function() {
  var Grid, Square, calcGridCoords, clickMod, get_random_color, updateCoordinates;

  Square = (function() {

    function Square(color, width, height) {
      this.color = color;
      this.width = width;
      this.height = height;
    }

    return Square;

  })();

  Grid = (function() {
    var squares;

    squares = [];

    function Grid(gwidth, gheight, swidth, sheight) {
      var color, i, j, _i, _j, _ref, _ref1;
      this.gwidth = gwidth;
      this.gheight = gheight;
      this.swidth = swidth;
      this.sheight = sheight;
      for (i = _i = 0, _ref = gheight - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        squares[i] = [];
        for (j = _j = 0, _ref1 = gwidth - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
          color = get_random_color();
          squares[i][j] = new Square(color, swidth, sheight);
        }
      }
    }

    Grid.prototype.printGridInfo = function() {
      var sq, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = squares.length; _i < _len; _i++) {
        sq = squares[_i];
        _results.push(document.getElementById("msgs").innerHTML += "" + sq.color + ", " + sq.width + ", " + sq.height);
      }
      return _results;
    };

    Grid.prototype.drawGrid = function() {
      var arr, canvas, ctx, l_o_x, l_o_y, r_u_x, r_u_y, sq, x, y, _i, _len, _results;
      canvas = document.getElementById("dynCan");
      ctx = canvas.getContext("2d");
      _results = [];
      for (y = _i = 0, _len = squares.length; _i < _len; y = ++_i) {
        arr = squares[y];
        _results.push((function() {
          var _j, _len1, _results1;
          _results1 = [];
          for (x = _j = 0, _len1 = arr.length; _j < _len1; x = ++_j) {
            sq = arr[x];
            ctx.fillStyle = sq.color;
            l_o_x = sq.width * x;
            l_o_y = sq.height * y;
            r_u_x = sq.width * (x + 1);
            r_u_y = sq.height * (y + 1);
            _results1.push(ctx.fillRect(l_o_x, l_o_y, r_u_x, r_u_y));
          }
          return _results1;
        })());
      }
      return _results;
    };

    Grid.prototype.redrawSquare = function(_arg) {
      var sq, x, y;
      x = _arg[0], y = _arg[1];
      sq = squares[y][x];
      sq.color = get_random_color();
      return this.drawGrid();
    };

    return Grid;

  })();

  window.canvyClick = function(event) {
    var canvas, x, y;
    event = event || window.event;
    canvas = document.getElementById("dynCan");
    x = event.pageX - canvas.offsetLeft;
    y = event.pageY - canvas.offsetTop;
    updateCoordinates(x, y);
    return clickMod(x, y);
  };

  clickMod = function(x, y) {
    return tmp.redrawSquare(calcGridCoords(x, y));
  };

  calcGridCoords = function(x, y) {
    var gr_x, gr_y;
    gr_x = Math.floor(x / tmp.swidth);
    gr_y = Math.floor(y / tmp.sheight);
    return [gr_x, gr_y];
  };

  updateCoordinates = function(x, y) {
    $("#x_grid").text(x);
    return $("#y_grid").text(y);
  };

  get_random_color = function() {
    var color, i, letters, _i;
    letters = '0123456789ABDCEF'.split('');
    color = '#';
    for (i = _i = 0; _i <= 5; i = ++_i) {
      color += letters[Math.round(Math.random() * 15)];
    }
    return color;
  };

  document.write("<p>Dies ist ein durch ein KaffeeSkript                erzeugter Paragraph</p>                <canvas id='dynCan' width='150' height='150'                style='border:1px solid #000000;'                onclick='window.canvyClick()'></canvas>                               <p>Grid: X: <b id='x_grid'> no x_grid </b> |                 Y: <b id='y_grid'> no y_grid </b></p>");

  this.tmp = new Grid(15, 15, 10, 10);

  tmp.drawGrid(document.getElementById("dynCan"));

}).call(this);
