// Generated by CoffeeScript 1.3.3
var canvyClick;

  canvyClick = function(event) {
    var canvas, x, y;
    event = event || window.event;
    canvas = document.getElementById("canvy");
    x = event.pageX - canvy.offsetLeft;
    y = event.pageY - canvy.offsetTop;
    return alert("from deeds:" + x + " " + y);
  };
