// Generated by CoffeeScript 1.3.3
canvyClick;

  canvyClick = function(event) {
    var canvas, x, y;
    event = event || window.event;
    canvas = document.getElementById("dynCan");
    x = event.pageX - dynCan.offsetLeft;
    y = event.pageY - dynCan.offsetTop;
    document.getElementById("x_coord").innerHTML = x;
    return document.getElementById("y_coord").innerHTML = y;
  };

