// Generated by CoffeeScript 1.3.3
(function() {
  var addColors, hex, unhex, unhsgl, _addColors;

  addColors = function(c1, c2) {
    var blue, green, red, result;
    red = unhex(c1.slice(0, 2)) + unhex(c2.slice(0, 2));
    green = unhex(c1.slice(2, 4)) + unhex(c2.slice(2, 4));
    blue = unhex(c1.slice(4, 6)) + unhex(c2.slice(4, 6));
    red %= 256;
    green %= 256;
    blue %= 256;
    return result = hex(red) + hex(green) + hex(blue);
  };

  _addColors = function(c1, c2) {
    var unh_c1, unh_c2;
    unh_c1 = unhex(c1);
    unh_c2 = unhex(c2);
    return hex(unh_c1 + unh_c2);
  };

  unhex = function(hex) {
    var h, k, result, _i, _len;
    k = hex.length - 1;
    result = 0;
    for (_i = 0, _len = hex.length; _i < _len; _i++) {
      h = hex[_i];
      result += Math.pow(16, k) * (unhsgl(h));
      k--;
    }
    return result;
  };

  unhsgl = function(hex) {
    var unhx;
    unhx = "0123456789ABCDEF";
    return unhx.indexOf(hex);
  };

  hex = function(dec) {
    var hexes, i, reste, value;
    hexes = "0123456789ABCDEF";
    reste = "";
    value = dec;
    i = 2;
    while ((value > 0) || (i > 0)) {
      reste = hexes[value % 16] + reste;
      value = Math.floor(value / 16);
      i -= 1;
    }
    return reste;
  };

  addColors("FF0000", "0000FF");

}).call(this);
